FROM php:8.2-fpm

# Define argumentos com valores padrão
ARG user=www-data
ARG uid=1000

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    git \
    cron \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libssl-dev \
    tzdata \
    && cp /usr/share/zoneinfo/America/Fortaleza /etc/localtime \
    && echo "America/Fortaleza" > /etc/timezone \
    && apk del tzdata

# Instalar extensões do PHP
RUN pecl install mongodb \
    && docker-php-ext-enable mongodb \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo zip gd
  

# Obter a última versão do Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Configura o timezone no PHP
RUN echo "date.timezone=America/Fortaleza" >> /usr/local/etc/php/conf.d/timezone.ini  

# Definir diretório de trabalho
WORKDIR /var/www/html

# Copiar o código da aplicação para a imagem final
#COPY . .

# Após COPY . .
# Instalar dependências do Composer
#RUN composer install --no-interaction --optimize-autoloader

# Definir permissões corretas
#RUN chown -R www-data:www-data /var/www/html/storage \
#    && chmod -R 775 /var/www/html/storage \
#    && chown -R www-data:www-data /var/www/html/bootstrap/cache \
#    && chmod -R 775 /var/www/html/bootstrap/cache

# Criar script de entrypoint para configuração do PHP-FPM
EXPOSE 9000
